repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.4
    hooks:
      - id: isort
        args: []
        additional_dependencies: [toml]
        exclude: docs/tutorials

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/dfm/black_nbconvert
    rev: stable
    hooks:
      - id: black_nbconvert
