trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p build
    cd build
    cmake ..
    make
  displayName: 'Build'

- script: |
    cd build
    CTEST_OUTPUT_ON_FAILURE=1 make test
  displayName: 'Test'
