trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: CMake@1
#   inputs:
#     workingDirectory: "build"
#   #   #cmakeArgs: # Optional
#   displayName: 'Build the code'

- script: |
    mkdir -p build
    cd build
    echo `which cmake`
    cmake ..
    make VERBOSE=1
  displayName: 'Build'

- script: |
    cd build
    make test
  displayName: 'Test'
