trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p build
    cd build
    cmake ..
    make
  displayName: 'Build'

- script: |
    cd build
    make test
  displayName: 'Test'
