trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p c++/build
    cd c++/build
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    make -j2
  displayName: 'Build'

- script: |
    cd c++/build
    CTEST_OUTPUT_ON_FAILURE=1 make test
  displayName: 'Test'
