name: Windows
on: [push, pull_request]

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda create -n celerite2 python=3.7 -q -c conda-forge
          conda activate celerite2
          conda install -c conda-forge -q "numpy=1.16.5" mkl-service libpython m2w64-toolchain
          python -m pip install -e ".[test]"
      - name: Run tests
        run: |
          conda activate celerite2
          python -m pytest -v python/test
